#+TITLE: Shell Configuration for MacOS
#+AUTHOR: Aleksandr Ivanov
#+BABEL: :cache yes

* ZSH Configuration for MacOS
  This file contains an untangle, Borg-based configuration for my shell-environment
** Essentials  
Essentials environment variables.
 - [ ] #TODO :: Probably Homebrew config doesn't really belong here.

#+BEGIN_SRC sh 
export TERM=xterm-256color
export LANG=en_US.UTF-8
export EDITOR=emacs
export HOMEBREW_PREFIX=/usr/local
#+END_SRC

This sections makes a bunch of fixes:
 - Set the size of tabs. For some reason my default size if 8, which i'm not happy with. Probably this should be better configured via the terminal, but i haven't seen anything
 - Support for better colouring 

#+BEGIN_SRC sh
tabs 4
autoload -U colors && colors
#+END_SRC   
 
** Preparing ZSH 
#+BEGIN_SRC sh
echo "\n$fg[green][Preparing ZSH]$reset_color"
#+END_SRC

#+BEGIN_SRC sh
  export ZSH=$HOME/.oh-my-zsh
  ZSH_THEME="ys"
  plugins=(
      # shell extension to jump to frequently used directories
      autojump
      # Homebrew support
      brew 
      # adds colors to manpages
      colored-man-pages 
      # cat with syntax highlight support
      colorize
      # Self descriptive
      per-directory-history
      # extras: git-extras gitfast git-flow git-flow-avh git-hubflow git-remote-branch
      git 
      # Autocomplete
      scala 
      # autocomplete for ScalaBuildTool http://www.scala-sbt.org/
      sbt 
      # Obviously docker autocomplete support
      docker)
  echo "Enabled Plugins:"
  for p in $plugins 
  do
      echo "- [x] $p"
  done
  source $ZSH/oh-my-zsh.sh
#+END_SRC

** Preparing Java
#+BEGIN_SRC sh
echo "\n$fg[green][Language: Java]$reset_color"
#+END_SRC

#+BEGIN_SRC sh
JAVA_VERSION=1.8.0_131
export JAVA_HOME=`/usr/libexec/java_home -v $JAVA_VERSION`
java -version
#+END_SRC

** Preparing LLVM & C/C++
#+BEGIN_SRC sh
echo "\n$fg[green][Language: C/C++]$reset_color"
#+END_SRC

#+BEGIN_SRC sh
export PATH="/usr/local/opt/llvm/bin:$PATH"
clang --version
#+END_SRC
** Rust language support
#+BEGIN_SRC sh
echo "\n$fg[green][Language: Rust]$reset_color"
#+END_SRC

#+BEGIN_SRC sh
source $HOME/.cargo/env
rustc --version
cargo --version
#+END_SRC
** Additional plugins
#+BEGIN_SRC sh
echo "\n$fg[green][Additional Plugins]$reset_color"
#+END_SRC
*** ZSH Highlighting
#+BEGIN_SRC sh
echo "- [x] ZSH Highlighting"
source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
#+END_SRC    
*** Autojump
#+BEGIN_SRC sh
echo "- [x] Autojump"
[ -f /usr/local/etc/profile.d/autojump.sh ] && . /usr/local/etc/profile.d/autojump.sh
#+END_SRC
*** GNU Global
#+BEGIN_SRC sh
echo "- [x] GNU Global"
export GTAGSCONF=/usr/local/share/gtags/gtags.conf
export GTAGSLABEL=new-ctags
#+END_SRC
** Aliases
*** Homebrew support
#+BEGIN_SRC sh
alias bubu="brew update && brew upgrade"
#+END_SRC

* TODOs
 - [ ] Add description how to tangle this file using Org-mode
 - [ ] Bootstrap configuration using =.el= script
 - [ ] Need to add some checks for ZSH installation
